local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', function ()
    builtin.find_files({hidden = true, layout_strategy = "vertical", selection_caret = " ", prompt_prefix = "󰭹  "})
end)
vim.keymap.set('n', '<leader>g', builtin.git_files, {})
vim.keymap.set('n', '<leader>s', function()
	builtin.grep_string({ search = vim.fn.input("Grep > "), use_regex = true, selection_caret = " ", prompt_prefix = "󰭹  "})
end)
vim.keymap.set('n', '<leader>lg', function ()
    builtin.live_grep({ selection_caret = " ", prompt_prefix = "󰭹  "})
end)
